version: '3.8'

services:
  nginx1:
    image: 'nginx:stable'
    ports:
      - '127.0.0.1:8000:80'
    volumes:
      - ./nginx1/conf.d:/etc/nginx/conf.d:ro
      - ./nginx1/nginx.conf:/etc/nginx/nginx.conf:ro
  nginx2:
    image: 'nginx:stable'
    ports:
      - '127.0.0.1:8001:80'
    volumes:
      - ./nginx2/conf.d:/etc/nginx/conf.d:ro
      - ./nginx2/nginx.conf:/etc/nginx/nginx.conf:ro
  test1:
    build:
      context: ./node
      dockerfile: dockerfile
    env_file:
      - ./env/node1.env
    cpus: ".25" # CPU 프로세스 사용률 25%로 제한
    mem_limit: "2g" # 2GB로 메모리 제한
  test2:
    build:
      context: ./node
      dockerfile: dockerfile
    env_file:
      - ./env/node2.env
    cpus: ".25" # CPU 프로세스 사용률 25%로 제한
    mem_limit: "2g" # 2GB로 메모리 제한
  test3:
    build:
      context: ./node
      dockerfile: dockerfile
    env_file:
      - ./env/node3.env
    cpus: ".25" # CPU 프로세스 사용률 25%로 제한
    mem_limit: "2g" # 2GB로 메모리 제한
  test4:
    build:
      context: ./node
      dockerfile: dockerfile
    env_file:
      - ./env/node4.env
    cpus: ".25" # CPU 프로세스 사용률 25%로 제한
    mem_limit: "2g" # 2GB로 메모리 제한
  test5:
    build:
      context: ./node
      dockerfile: dockerfile
    env_file:
      - ./env/node5.env
    cpus: ".25" # CPU 프로세스 사용률 25%로 제한
    mem_limit: "2g" # 2GB로 메모리 제한
  test6:
    build:
      context: ./node
      dockerfile: dockerfile
    env_file:
      - ./env/node6.env
    cpus: ".25" # CPU 프로세스 사용률 25%로 제한
    mem_limit: "2g" # 2GB로 메모리 제한